name: Build Module
on:
    pull_request: # Only trigger the workflow if there is a pull request to the main branch
        branches: [ main ]

    workflow_dispatch: # Enables the possibility to trigger the workflow manually

jobs:
    # first job builds the module
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - name: Install and cache PowerShell modules
              id: psmodulecache
              uses: potatoqualitee/psmodulecache@v4.5
              with:
                modules-to-cache: Pester, PSSCriptAnalyzer, InvokeBuild, platyPS

            - name: Invoke Build
              shell: pwsh
              run: pwsh -Command "Invoke-Build -file ./IvantiPS.build.ps1 -Configuration 'Release' -ExportAlias"

            #- name: Push changes to Git Repository
            #  run: |
            #    git config --global user.name 'Joseph'
            #    git config --global user.email 'joey.was@gmail.com'
            #    git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            #    git add .
            #    git commit -am "Pushing Artifacts"
            #    git push
            
            - name: Upload Build Artifact
              uses: actions/upload-artifact@v3
              with:
                name: module-artifact # naming the powershell module artifact
                path: ./Output/ # saving the powershell module artifact to the path .Output/